# Generated by Django 6.0.6 on 2026-06-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(db_index=True, max_length=20, verbose_name='السجل المدني')),
                ('found', models.BooleanField(default=False, verbose_name='وجد نتيجة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='المتصفح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سجل دخول',
                'verbose_name_plural': 'سجلات الدخول',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RenewalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(db_index=True, max_length=20, verbose_name='السجل المدني')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('school_name', models.CharField(blank=True, max_length=255, verbose_name='المدرسة')),
                ('sector', models.CharField(blank=True, max_length=255, verbose_name='القطاع التعليمي')),
                ('category', models.CharField(blank=True, max_length=120, verbose_name='الفئة')),
                ('raw_status', models.CharField(blank=True, max_length=255, verbose_name='الحالة الأصلية')),
                ('status_key', models.CharField(blank=True, max_length=60, verbose_name='رمز الحالة')),
                ('status_label', models.CharField(blank=True, max_length=120, verbose_name='الحالة المعروضة')),
                ('status_message', models.TextField(blank=True, verbose_name='رسالة الحالة')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سجل استعلام',
                'verbose_name_plural': 'سجلات الاستعلام',
                'ordering': ['full_name'],
            },
        ),
    ]
